### ISSUE TITLE
Artisans will skipped when reach 1000+

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#4] opened 2019-08-27 11:40 UTC
Final Results of the 1.1.3 Artisans (#3):

After couple of tests i have found the following issue for Island Population: 
When artisans stay under (or is 999) then the server will push the numbers to the website, but when you reach 1000 or more Artisans the push will not be done (changed to 0), while the server sees the right numbers (see screen 1 in #3)
After you reach the first Engineer, it will show up again on the website, regardless the count (under or above the 1000)

Hope this will help you to pinpoint the issue

Note  On Global Populations all things works fine

**Comment by Dejauxvue** [comment] 2019-08-27 18:43
Thank you very much for your extensive testing!
It will definitely help
You can expect a new release around monday

**Comment by Dejauxvue** [comment] 2019-08-27 20:38
one more thing:
Could you post a screenshot of your game while this bug occurs? (With visible Island population)

**Comment by StingMcRay** [comment] 2019-08-29 14:49
I will do : i just load an older save then

**Comment by StingMcRay** [comment] 2019-08-29 15:03
Under 1000 : 
![afbeelding](https://user-images.githubusercontent.com/18048706/63951698-848c7b80-ca7e-11e9-9adc-f6b763fea6d0.png)

1010+
![afbeelding](https://user-images.githubusercontent.com/18048706/63951899-daf9ba00-ca7e-11e9-8ccb-512fb52c0603.png)

It seams that till 1010 *narrow it down to* the numbers are going to the site, but when hit 1010 or higher then its gone to 0 on website

**Comment by NiHoel** [comment] 2019-08-29 16:24
The problem is that text recognition is rather instable. Here, it detects Aisans instead of Artisans. Currently, regular expressions are used to test whether its (a variant of) a searched word (Farmers, Workers, Artisans, ...). If it is not found, we assume this population tier is not present in the list nor on the island -> enter 0.  
See line 432 in [https://github.com/Dejauxvue/AnnoCalculatorServer/blob/master/cpp/visual%20studio/CalculatorServer/Server/image_recognition.cpp](https://github.com/Dejauxvue/AnnoCalculatorServer/blob/master/cpp/visual%20studio/CalculatorServer/Server/image_recognition.cpp)
If we allow more variants (e.g. by using longest common subsequences as a matching criterion), the problem of missclassifications arises.

Concerning the problem with Jornaleros described in [#3](https://github.com/Dejauxvue/AnnoCalculatorServer/issues/3#issuecomment-525217405): This might be due to the last digit of the number not being detected. Could you please send us a screenshot (like the ones above) that shows this issue?

**Comment by StingMcRay** [comment] 2019-08-29 17:00
I will do that when i enter that test phase for you guys :) my wife moved on with the game so.. i will test and do it my self instead :) (will be done before weekend i hope)

**Comment by StingMcRay** [comment] 2019-08-29 17:57
As for now i can not reproduce the error my wive had, when i have i will make a new issue to the matter i called in #3

**Comment by NiHoel** [comment] 2019-08-30 21:00
@StingMcRay Try this new server version and tell us whether it fixes the issues. Please notify us immediately if new problems occur (false positive detection, wrong numbers, ...).

Thanks a lot for your help. Without you we'd never detected those issues.

[AnnoServer.zip](https://github.com/Dejauxvue/AnnoCalculatorServer/files/3561514/AnnoServer.zip)

**Comment by Dejauxvue** [comment] 2019-09-15 18:46
Could you test this issue under the new release? and close it if it works

**Closed as completed** 2019-12-15 00:00 UTC
